### ISSUE TITLE
Reporting Errors 

### ISSUE THREAD

**Issue by kaypiob** [ProtDos/boosint#4]
I'm receiving the below errors when attempting to run the program. I'm on MacOS Ventura. Wondering if maybe an update is needed?

Traceback (most recent call last):
  File "[redacted by me]/boosint/boosint.py", line 86, in <module>
    git = github.github(username)
  File "[redacted by me]/boosint/modules/github.py", line 12, in github
    driver = webdriver.Chrome(options=chrome_options, executable_path="/Driver/chromedriver.exe")
TypeError: __init__() got an unexpected keyword argument 'executable_path'

**Comment by ProtDos** [comment]
I'll have a look at it when I am home.
